# Generated by Django 2.2.1 on 2019-05-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_display'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guage',
            new_name='Gauge',
        ),
    ]
