# Generated by Django 2.2.1 on 2019-06-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statlord', '0002_layout_display_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='display_data',
            field=models.TextField(default=''),
        ),
    ]
